GET https://api.covid19india.org/states_daily.json
Accept: application/json


###


GET https://api.covid19india.org/zones.json
Accept: application/json


###
GET https://api.rootnet.in/covid19-in/contacts
Accept: application/json